version: '3.8'

services:

  site1:
    image: nginx
    container_name: site1
    volumes:
      - ./site1:/usr/share/nginx/html
    restart: always

  site2:
    image: nginx
    container_name: site2
    volumes:
      - ./site2:/usr/share/nginx/html
    restart: always

  reverse_proxy:
    image: nginx
    container_name: reverse_proxy
    ports:
      - "80:80"   # ðŸ”¥ THIS WAS MISSING
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - site1
      - site2
    restart: always

